# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "capistrano-shared_file"
  s.version = "0.1.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["teohm"]
  s.date = "2012-05-11"
  s.description = "Capistrano recipe to symlink shared files e.g. config/database.yml"
  s.email = "teohuiming@gmail.com"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "capistrano-shared_file.gemspec",
    "lib/capistrano/shared_file.rb"
  ]
  s.homepage = "http://github.com/teohm/capistrano-shared_file"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.24"
  s.summary = "Capistrano recipe to symlink shared files e.g. config/database.yml"

  s.add_runtime_dependency('capistrano', "~>2.0")
  s.add_development_dependency('bundler')
  s.add_development_dependency('rdoc')
  s.add_development_dependency('jeweler')
end
